[package]
name = "c3-sos-ical-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.19"
icalendar = { version = "0.17.6", features = ["chrono-tz", "serde"] }
chrono = "0.4"
